const ALERT = "ALERT";
const REFETCH_CHAT = "REFETCH_CHAT";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE_ALERT = "NEW_MESSAGE_ALERT";
const NEW_REQUEST = "NEW_REQUEST";
const NEW_MESSAGE = "NEW_MESSAGE";
const START_TYPING = "START_TYPING";
const STOP_TYPING = "STOP_TYPING";
const CHAT_JOINED = "CHAT_JOINED";
const CHAT_LEAVED = "CHAT_LEAVED";
const ONLINE_USERS = "ONLINE_USERS";
const OFFER_CALL = "OFFER_CALL";
const ANSWER_CALL = "ANSWER_CALL";
const INCOMING_CALL = "INCOMING_CALL";
const MISSED_CALL = "MISSED_CALL";

export {
  ALERT,
  REFETCH_CHAT,
  NEW_ATTACHMENT,
  NEW_MESSAGE_ALERT,
  NEW_REQUEST,
  NEW_MESSAGE,
  START_TYPING,
  STOP_TYPING,
  CHAT_LEAVED,
  CHAT_JOINED,
  ONLINE_USERS,
  OFFER_CALL,
  ANSWER_CALL,
  INCOMING_CALL,
  MISSED_CALL,
};
